/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.foobaz42.comparatorverifier;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        ComparatorVerifier classUnderTest = new ComparatorVerifier();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
